version: '2'
services:
  selenium-chrome:
    ports:
     - "4444:4444"
    image: selenium/standalone-chrome
  tests-wordpress:
    image: wordpress:latest
    links:
      - wordpress
      - selenium-chrome
    volumes:
     - .:/var/www/wordpress/
    working_dir: /var/www/wordpress/
    command: bash -c 'sleep 5 ; ./vendor/behat/behat/bin/behat'
